spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: aaaaa@qq.com
    password: aaaaa # 授权码
  redis:
    host: 127.0.0.1
#    password: root
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    show-sql: true



server:
  port: 8002
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    cn.ecut: debug



travel:
  host: http://localhost:${server.port}/
file:
  upload-dir: D:\\resources\\upload\\


